environ


  vocabularies SUBSET_1, XBOOLE_0, TARSKI, ZFMISC_1;
     notations TARSKI, XBOOLE_0, SUBSET_1, ZFMISC_1;

begin 

theorem Th3  :
    for a ,b being   set holds a is Subset of iff a c= b
    proof let a  ,b be set;
    hereby
    assume a is Subset of b  ;then a in bool b by SUBSET_1  :def 1 ;hence a c= b by ZFMISC_1;
    end;assume a c= b; then a   in bool b by ZFMISC_1  :  def 1; hence thesis by SUBSET_1:def 1;end;



