environ

 vocabularies SUBSET_1, XBOOLE_0, TARSKI, ZFMISC_1;
 notations TARSKI, XBOOLE_0, SUBSET_1, ZFMISC_1;
 constructors TARSKI, SUBSET_1;
 registrations SUBSET_1;
 requirements BOOLE;
 theorems TARSKI, SUBSET_1, ZFMISC_1;

begin


theorem
  for a, b, c being set st a in b & b is Subset of c holds a is Element of c
proof
  let a, b, c be set;
  assume that
A1: a in b and
A2: b is Subset of c;
  b c= c by A2,Th3;
  then a in c by A1,TARSKI:def 3;
  hence thesis by SUBSET_1:def 1;
end;